postgresql_db:
  name: "postgresql-db"
  inner_port: 5432
  external_port: 5432
  secrets:
    hostname: "postgres"
    db: "postgres"
    username: "postgres"
    password: "postgres"
  deployment:
    replicas: 1
    image: "postgres:latest"
    restartPolicy: Always
  service:
    type: LoadBalancer

config:
  name: "config"
  inner_port: 8762
  external_port: 8762
  pod:
    image: "izouir/fm-config:1.0"
    restartPolicy: OnFailure
  service:
    type: LoadBalancer

db_migration:
  name: "db-migration"
  pod:
    image: "izouir/fm-db-migration:1.0"
    restartPolicy: OnFailure

discovery:
  name: "discovery"
  inner_port: 8761
  external_port: 8761
  pod:
    image: "izouir/fm-discovery:1.0"
    restartPolicy: OnFailure
  service:
    type: LoadBalancer

transaction:
  name: "transaction"
  deployment:
    replicas: 2
    image: "izouir/fm-transaction:1.0"
    restartPolicy: Always

budget_planning:
  name: "budget-planning"
  deployment:
    replicas: 2
    image: "izouir/fm-budget-planning:1.0"
    restartPolicy: Always

gateway:
  name: "gateway"
  inner_port: 8765
  external_port: 8765
  deployment:
    replicas: 3
    image: "izouir/fm-gateway:1.0"
    restartPolicy: Always
  service:
    type: LoadBalancer

keycloak:
  name: "keycloak"
  inner_port: 8080
  external_port: 8080
  secrets:
    kc_bootstrap_admin_username: "admin"
    kc_bootstrap_admin_password: "admin"
    kc_db: "postgres"
  deployment:
    replicas: 1
    image: "quay.io/keycloak/keycloak:26.0.0"
#    restartPolicy: Always
  service:
    type: LoadBalancer