name: finance-manager
services:
  postgresql-db:
    container_name: ${POSTGRES_HOSTNAME}
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  config:
    container_name: config
    build: ../config-service
    environment:
      CONFIG_PORT: ${CONFIG_PORT}
    restart: on-failure

  db-migration:
    container_name: db-migration
    build: ../db-migration-service
    restart: on-failure
    environment:
      CONFIG_PORT: ${CONFIG_PORT}
      DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - config
      - postgresql-db

  discovery:
    container_name: discovery
    build: ../discovery-service
    restart: on-failure
    environment:
      CONFIG_PORT: ${CONFIG_PORT}
      DISCOVERY_PORT: ${DISCOVERY_PORT}
    depends_on:
      - config
    ports:
      - ${DISCOVERY_PORT}:${DISCOVERY_PORT}

  transaction:
    container_name: transaction
    build: ../transaction-service
    restart: on-failure
    environment:
      CONFIG_PORT: ${CONFIG_PORT}
      DISCOVERY_PORT: ${DISCOVERY_PORT}
      DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - discovery

  budget-planning:
    container_name: budget-planning
    build: ../budget-planning-service
    restart: on-failure
    environment:
      CONFIG_PORT: ${CONFIG_PORT}
      DISCOVERY_PORT: ${DISCOVERY_PORT}
      DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
      DATASOURCE_USERNAME: ${POSTGRES_USER}
      DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - discovery

  gateway:
    container_name: gateway
    build: ../gateway-service
    restart: on-failure
    environment:
      CONFIG_PORT: ${CONFIG_PORT}
      DISCOVERY_PORT: ${DISCOVERY_PORT}
      GATEWAY_PORT: ${GATEWAY_PORT}
      KEYCLOAK_PORT: ${KEYCLOAK_PORT}
    depends_on:
      - discovery
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    command: start-dev --health-enabled=true
    depends_on:
      - postgresql-db
    ports:
      - ${KEYCLOAK_PORT}:8080