spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    jpa:
      show-sql: false
      generate-ddl: false
      hibernate:
        ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:${KAFKA_PORT}
    consumer:
      group-id: "transaction"
      auto-offset-reset: earliest
      properties:
        topic-transaction: "transaction"
    producer:
      properties:
        topic-goal: "goal"
        topic-limitation: "limitation"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"