spring:
  kafka:
    bootstrap-servers: kafka:${KAFKA_PORT}
    consumer:
      group-id: "notification"
      auto-offset-reset: earliest
      properties:
        topic-goal: "goal"
        topic-limitation: "limitation"

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:${DISCOVERY_PORT}/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"